<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="8.15.0" />
    <PackageReference Include="Npgsql" Version="9.0.4" />
    <PackageReference Include="Weasel.Postgresql" Version="8.3.0" />
  </ItemGroup>

</Project>
