services:
  postgres:
    image: postgres:16
    container_name: dp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TicketDb
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: dp-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SqlStr0ng!Passw0rd
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
      - ./sqlserver-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: dp-adminer
    ports:
      - "8088:8080"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  pgdata:
  mssqldata:
